on:
  push:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: github-actions-up-and-running/pr-comment@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: atlantis plan
          
        
